from linear_model.linear_model import LinearModel
from linear_model.linear_regression import LinearRegression
from linear_model.ridge_regression import RidgeRegression
from linear_model.lasso_regression import LassoRegression
from linear_model.elastic_net import ElasticNet
from linear_model.logistic_regression import LogisticRegression
from linear_model.softmax_regression import SoftmaxRegression

# aliasing
SoftmaxClassification = SoftmaxRegression
LogisticRegression = LogisticClassification
